///
/// Code generated by jsonToDartModel http://json.fluttergeeks.in/
///
class UpComingModelAllMatch {
/*
{
  "Title": "PSL 11th T20 Match",
  "Matchtime": "22-Feb-2023 at 06:00PM-Wed",
  "Venue": "Multan Cricket Stadium, Multan",
  "MatchId": 0,
  "TeamA": "Multan Sultans",
  "TeamB": "Karachi Kings",
  "TeamAImage": "Multan_Sultans.jpg",
  "Matchtype": null,
  "TeamBImage": "Karachi_Kings.png",
  "Result": null,
  "ImageUrl": "http://cricnet.co.in/ManagePlaying/TeamImages/"
}
*/

  String? Title;
  String? Matchtime;
  String? Venue;
  int? MatchId;
  String? TeamA;
  String? TeamB;
  String? TeamAImage;
  String? Matchtype;
  String? TeamBImage;
  String? Result;
  String? ImageUrl;

  UpComingModelAllMatch({
    this.Title,
    this.Matchtime,
    this.Venue,
    this.MatchId,
    this.TeamA,
    this.TeamB,
    this.TeamAImage,
    this.Matchtype,
    this.TeamBImage,
    this.Result,
    this.ImageUrl,
  });
  UpComingModelAllMatch.fromJson(Map<String, dynamic> json) {
    Title = json['Title']?.toString();
    Matchtime = json['Matchtime']?.toString();
    Venue = json['Venue']?.toString();
    MatchId = json['MatchId']?.toInt();
    TeamA = json['TeamA']?.toString();
    TeamB = json['TeamB']?.toString();
    TeamAImage = json['TeamAImage']?.toString();
    Matchtype = json['Matchtype']?.toString();
    TeamBImage = json['TeamBImage']?.toString();
    Result = json['Result']?.toString();
    ImageUrl = json['ImageUrl']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Title'] = Title;
    data['Matchtime'] = Matchtime;
    data['Venue'] = Venue;
    data['MatchId'] = MatchId;
    data['TeamA'] = TeamA;
    data['TeamB'] = TeamB;
    data['TeamAImage'] = TeamAImage;
    data['Matchtype'] = Matchtype;
    data['TeamBImage'] = TeamBImage;
    data['Result'] = Result;
    data['ImageUrl'] = ImageUrl;
    return data;
  }
}

class UpComingModel {
/*
{
  "Playerslist": null,
  "AllMatch": [
    {
      "Title": "PSL 11th T20 Match",
      "Matchtime": "22-Feb-2023 at 06:00PM-Wed",
      "Venue": "Multan Cricket Stadium, Multan",
      "MatchId": 0,
      "TeamA": "Multan Sultans",
      "TeamB": "Karachi Kings",
      "TeamAImage": "Multan_Sultans.jpg",
      "Matchtype": null,
      "TeamBImage": "Karachi_Kings.png",
      "Result": null,
      "ImageUrl": "http://cricnet.co.in/ManagePlaying/TeamImages/"
    }
  ],
  "success": true,
  "msg": "Data Fetched"
}
*/

  String? Playerslist;
  List<UpComingModelAllMatch>? AllMatch;
  bool? success;
  String? msg;

  UpComingModel({
    this.Playerslist,
    this.AllMatch,
    this.success,
    this.msg,
  });
  UpComingModel.fromJson(Map<String, dynamic> json) {
    Playerslist = json['Playerslist']?.toString();
    if (json['AllMatch'] != null) {
      final v = json['AllMatch'];
      final arr0 = <UpComingModelAllMatch>[];
      v.forEach((v) {
        arr0.add(UpComingModelAllMatch.fromJson(v));
      });
      AllMatch = arr0;
    }
    success = json['success'];
    msg = json['msg']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['Playerslist'] = Playerslist;
    if (AllMatch != null) {
      final v = AllMatch;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['AllMatch'] = arr0;
    }
    data['success'] = success;
    data['msg'] = msg;
    return data;
  }
}
